# version: "3.8"

# services:
#   db:
#     image: postgres:latest
#     container_name: postgres_db
#     restart: always
#     ports:
#       - "5432:5432"
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: chetan
#       POSTGRES_DB: UserData
#     networks:
#       - my_network
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

#   fastapi:
#     build: .
#     container_name: fastapi_app
#     ports:
#       - "8002:8002"
#     depends_on:
#       - db
#     environment:
#       DATABASE_URL: postgresql://postgres:chetan@db:5432/UserData
#     networks:
#       - my_network

# networks:
#   my_network:
#     driver: bridge

# volumes:
#   postgres_data: