version: '3.9'

services:
  api:
    build: .
    container_name: youtube_api
    command: gunicorn app.main:app -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
      - redis
    restart: unless-stopped

  worker:
    build: .
    container_name: celery_worker
    command: celery -A app.Core.celery_worker.celery_worker.celery_app worker --loglevel=info
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - redis
      - db
    restart: unless-stopped
    tty: true
    stdin_open: true

  db:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: chetan
      POSTGRES_DB: UserData
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: redis_cache
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

volumes:
  postgres_data:
